{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httproute.name | default (include "gateway.fullname" .) }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httproute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.httproute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  rules:
    {{- range .Values.httproute.rules }}
    {{- with .matches }}
    - matches:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .backendRefs }}
      backendRefs:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}
{{- end }}

