{{- if not .Values.secret.external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default (include "backend.fullname" .) }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}

